# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18QudRyhbEkmaPFOhvoyqNd5BR4gR_nx1
"""

import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense

seed = 7
np.random.seed(seed)
from google.colab import files 
uploaded = files.upload()

dataset = pd.read_csv('train.csv',header = None)
print(dataset.head())

x_train = dataset.iloc[:,0:8]
y_train = dataset.iloc[:,8]

from google.colab import files 
uploaded = files.upload()

x_test = pd.read_csv('test.csv',header = None)
print(x_test.head())

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

classifier = Sequential()
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 8 ))
classifier.add(Dense(output_dim = 5, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 4, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(x_train, y_train, batch_size = 5, nb_epoch =100)

y_pred = classifier.predict(x_test)
y_pred = (y_pred > 0.5).astype(int)
print(y_pred)

