# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m1JlgeEW1-xNMIrt0-uDzH7hr1vgKk45
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files
uploaded= files.upload()

uploaded=files.upload()

data = pd.read_csv('train.csv')
X_train=data.iloc[:,0:8].values
Y_train=data.iloc[:,8].values
X_test=pd.read_csv('test.csv')

data=data.replace([np.nan],[0],inplace=True)

import keras
from keras.models import Sequential
from keras.layers import Dense
classifier= Sequential()

classifier.add(Dense(output_dim=5, init='uniform', activation='relu', input_dim=8))
classifier.add(Dense(output_dim=5 ,init='uniform', activation='relu'))
classifier.add(Dense(output_dim=1, init='uniform', activation='sigmoid'))

classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
#classifier.fit(X_train,Y_train,batch_size=10,nb_epoch=100)
classifier.fit(X_train, Y_train, batch_size = 10, nb_epoch = 100)

print(data.columns.values)

y_pred = classifier.predict(X_test)
y_pred=(y_pred>0.5)

np.savetxt('results.csv',y_pred,delimiter=',')

files.download('results.csv')